# Generated by Django 4.2.3 on 2024-05-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdata',
            name='book_publishdate',
        ),
        migrations.AddField(
            model_name='bookdata',
            name='book_price',
            field=models.IntegerField(default=1500),
            preserve_default=False,
        ),
    ]
